/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.itson.philadelphia.ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import mx.itson.philadelphia.entities.*;
import mx.itson.philadelphia.persistencia.*;

/**
 *
 * @author Christian
 */
public class GuardarMulta extends javax.swing.JDialog {
    
    int idMulta;

    /**
     * Creates new form GuardarMulta
     */
    public GuardarMulta(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        
        idMulta = id;
        
         DateFormat formato = new SimpleDateFormat("dd/MMMM/yyyy");
        
        cboDias.removeAllItems();
        cboAnios.removeAllItems();
        cboConductores.removeAllItems();
        cboOficiales.removeAllItems();
        
        agregarOficialesYConductores();
        CambiarDias();
        
        /*if(idMulta != 0){
            
            MultaDAO mul = new MultaDAO();
            Multa multa = mul.obtenerPorId(this.idMulta);
            
            txtFolio.setText(multa.getNombre());
            txtNumeroLicencia.setText(multa.getNumeroLicencia());
            Date fecha = multa.getFecha();
            String fech = formato.format(fecha);
            String f[] = fech.split("/");
            
            cboMeses.setSelectedItem(f[1]);
            cboDias.setSelectedItem(f[0]);
            cboAnios.setSelectedItem(f[2]);
            
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboMeses = new javax.swing.JComboBox<>();
        cboDias = new javax.swing.JComboBox<>();
        cboAnios = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        cboConductores = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboOficiales = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Folio");

        jLabel2.setText("Conductor");

        jLabel3.setText("Fecha de alta");

        cboMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboMeses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMesesItemStateChanged(evt);
            }
        });
        cboMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesesActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Oficial");

        jLabel5.setText("Motivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(cboMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFolio)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(cboConductores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(cboOficiales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMotivo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboConductores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboOficiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMesesItemStateChanged

        CambiarDias();

    }//GEN-LAST:event_cboMesesItemStateChanged

    private void cboMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMesesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try{

            SimpleDateFormat formato = new SimpleDateFormat("dd/MMMM/yyyy");

            String folio = txtFolio.getText();
            Conductor conductor = (Conductor)cboConductores.getSelectedItem();
            Oficial oficial = (Oficial)cboOficiales.getSelectedItem();
            String motivo = txtMotivo.getText();
            String fecha = cboDias.getSelectedItem().toString() + "/" + cboMeses.getSelectedItem().toString() + "/" + cboAnios.getSelectedItem().toString();
            Date fechaMulta = formato.parse(fecha);

            //boolean funco = this.idMulta == 0 ?
            //new MultaDAO().guardar(folio, motivo, fechaMulta, conductor, oficial);
            //new MultaDAO().editar(idConductor, nombre, numeroLicencia, fechaAlta);
            
            boolean funco = new MultaDAO().guardar(folio, motivo, fechaMulta, conductor, oficial);

            if(funco){

                JOptionPane.showMessageDialog(this, "El registro fue exitoso", "Guardado", JOptionPane.INFORMATION_MESSAGE);

                dispose();

            }else{

                JOptionPane.showMessageDialog(this, "El registro tuvo un error", "No guardado", JOptionPane.ERROR_MESSAGE);

                dispose();

            }

        }catch(Exception ex){

            System.err.println("Ocurrio un error: " + ex.getMessage());

        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    public void agregarOficialesYConductores(){
        
        ConductorDAO cn = new ConductorDAO();
        List<Conductor> conductores = cn.ObtenerTodos();
        OficialDAO of = new OficialDAO();
        List<Oficial> oficiales = of.ObtenerTodos();
        
        try{
            
            for(Conductor c : conductores){
            
                cboConductores.addItem(c);
            
            }
            
            for(Oficial o : oficiales){
            
                cboOficiales.addItem(o);
            
            }
            
        }catch(Exception ex){
            
            System.err.println("Ocurrio un error: " + ex.getMessage());
            
        }
        
    }
    
    public void CambiarDias(){
        
         try{
             
             int dia = 1;
             int i = 0;
             int a = 1900;
             
             while(a <= 2100){
                 
                 cboAnios.addItem(Integer.toString(a));
                 a++;
                 
             }
            
             if(cboMeses.getSelectedItem().toString().equals("January")){
                 
                 while(i <= 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("February")){
                 
                 while(i <= 29){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("March")){
                 
                 while(i <= 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("April")){
                 
                 while(i <= 30){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("May")){
                 
                 while(i <= 31){
                     
                    cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("June")){
                 
                 while(i <= 30){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("July")){
                 
                 while(i <= 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("August")){
                 
                 while(i <= 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("September")){
                 
                 while(i <= 30){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("October")){
                 
                 while(i <= 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("November")){
                 
                 while(i <= 30){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }else if(cboMeses.getSelectedItem().toString().equals("December")){
                 
                 while(i <= 31){
                     
                     cboDias.addItem(Integer.toString(dia));
                     i++;
                     dia++;
                     
                 }
                 
             }
                
            
        }catch(Exception ex){
            
            System.err.println("Ocurrio un error: " + ex.getMessage());
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuardarMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuardarMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuardarMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuardarMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuardarMulta dialog = new GuardarMulta(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboAnios;
    private javax.swing.JComboBox<Conductor> cboConductores;
    private javax.swing.JComboBox<String> cboDias;
    private javax.swing.JComboBox<String> cboMeses;
    private javax.swing.JComboBox<Oficial> cboOficiales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
